#!/bin/sh

# Colorize commands when possible.
alias \
	ls="exa --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
    v="nvim" \
    nv="nvim" \
    cat="bat" \
    vim="nvim"
