#! /bin/sh

$HOME/.config/bspwm/scripts/autostart.sh &

if [[ $(xrandr -q | grep -w '^HDMI.*connected') ]]; then
    $HOME/.config/bspwm/scripts/adjust_monitor.sh &
else
    bspc monitor -d 1 2 3 4 5
fi
#bspc monitor HDMI-0 -d 1 2 3 4
#bspc monitor eDP-1-1 -d 1 2 3 4

bspc config focused_border_color "#F9DE8F"
bspc config normal_border_color "#2b2f37"
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
