#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

$HOME/.config/polybar/launch.sh &

xrdb merge ~/.Xresources &

bspc monitor -d 1 2 3 4 5

#bspc config focused_border_color "#353b45"
#bspc config normal_border_color "#282c34"
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
